import type { Metadata } from "next";
import { Playfair_Display, Courier_Prime } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Emily Kontu - Costume Design",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  weight: "400",
});

const courier = Courier_Prime({
  subsets: ["latin"],
  variable: "--font-courier-prime",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} font-playfair, ${courier.variable} font-courier`}
    >
      <body>{children}</body>
    </html>
  );
}
